version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  assignees:
  - NorthernMan54
  labels:
    - "dependencies"
  # Group related updates together (optional)
  groups:
    packages:
      patterns:
        - "*"
  # Automatically rebase PRs when conflicts occur
  rebase-strategy: "auto"
  # Commit message prefix
  commit-message:
    prefix: "chore"
    prefix-development: "chore"
    include: "scope"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "09:00"
  # Create PRs for out-of-date actions
  open-pull-requests-limit: 10
  # Add labels to PRs
  labels:
    - "dependencies"
  # Group related updates together (optional)
  groups:
    actions:
      patterns:
        - "*"
  # Automatically rebase PRs when conflicts occur
  rebase-strategy: "auto"
  # Commit message prefix
  commit-message:
    prefix: "chore"
    prefix-development: "chore"
    include: "scope"